language: node_js
node_js:
- node
services:
- docker
before_script:
- npm install -g lab
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < lcov.info
before_install:
- docker build -t iromain/domain-tracker-api .
- echo $DOCKER_PASSWORD | docker login --username="$DOCKER_USERNAME" --password-stdin
- docker push iromain/domain-tracker-api
deploy:
  provider: heroku
  api_key:
    secure: gq0EZf+awlwlZbnOg6tR+Xax758QY6BU6kWXkTsd+xcsBZkOnA0ZyVFezza6u72YYvcs18fUZNlPhv3YgK0J4V+3Q2YU56JkFPDVu4udsf+NiEubNeKJgYIZGLR0Ts3PyALZwEorVYkD7kv2Y+amr8k1tRMf+xNb8PeuhRQTYkqLolZRXivQ6IfLAXHbR3FM7HNE+oxHnuWgTnHY9dYYY39BD4wfICARKEL+TuuZ7KWlYEhasSZfbm67YR+lnjflr96d785kBFmOQcWR50fCwaaXP/DcMfJq2rJWPAtZQX9t/4nseRhy7HwUiMowopUCttCK6T3RFbyA7YySScQXJOTxcqA9F8MNnRFmW4rWTARMKkJpBuQLSYnh9u+q9p+aMRDWo5Daw4Rc7bIlyraOg7ijifv+L6ztBsh7sXbxpOa02G69fq2YuAJMYqvrJaumFB8h2kyYuoAAfBkBpAXxLdztma1c3i4lzJTMjMQ941+I5SlpMLQs2wHhD3ydt6DBqkogLgUnkudsITcUPZE5fAAA9gfHr1qFPSsLebXpYb66787Sn9wgfz45xd+TmSB0SRm93FEE40Bd2ECXy/DzKwaIDVzwdg34hkGLfnAiUuOQcB/0hdnDdT7cZPVDmvHm8L4F+1tKmPWKTrQGYP+63HoesNG0De5Qmaj4gMWlRlA=
  app: domain-tracker-api
  on:
    repo: iRomain/domain-tracker-api
cache:
  directories:
  - node_modules
env:
  global:
  - NODE_ENV=test
  - DOCKER_USERNAME=iromain
  - secure: doTA/m0k7fwh5STxjhS6xvR+Pi5EkRK3/agO8NTPvo3H3VjHz4R7vN4rB0Gxe/CPi58yz1vmAuY+oiN3N3pJOH1v5h64gG8Bqn1KaAd3y/cE/xlkt5Nttr4QkQvwU+MDEQZDjcDWjP2xuuCLfg4pHPJvabVEN0yyYdWx5EzYKFiygVFLPPBKgtqljlxc/z16If2igaP7xP+JDwjaeN/V/29F+vo3hkPPSvFhr5GVy0AeQfJIO9E6puc0Q6Z8mVMwk4ThHS7UiW6A1s1vEsUajQTzY0sOgsUHNO9fVCtUHb0/+81hKCHD4NOQwmFOGTXqhn2kezqOazohjKYlQCnB5xI0Z2hQuBAcmdiuzMCVWY9R1bNQDNzEDKc+e7q65O2ab3npzJ7t11Pdn15WZBPTYflgnLAH5N36mahNiUYJgSBGZeWZ58K9h8Pgm5X7zRpQIvBQrDcCFRBpcmxD90AnciswjlqW3kArRq6CPn7R3Ye3ioTQqGPf6jUilsydpocWoECsNd6wn1VAr0wTS8q5oYwuP+AmWIejuzt5p8M+FiISZbQwcZzZGVOWSCOZwqzuPoSEedMoVNHj55geLB3WUvu8CKYSZCC3Obi1HZRnCPEX4H8kjV1aaMlgYstnmtIXVSbBlsyjP6rak3hzReO6rioZquVYKe9AjW4RBeH8tU0=
  - secure: VSppJD+TkHozdjBMceut5HzMRyLU7su+9r3K6zpGOC0g1KCufMdJKGYdxqslRv1QRAxod4fCGyFv4F1Qvu+e4nEUMRxuGQjo9GXhkU6Z1anKRbkVZ0Vpq+INIoFowB1j5qUKqsE5iARDPNHvN5vv+d6Jg/+2fP+SRUy06TiPT9Kz/TLNNB3pzAxplqO6xX4FB3xwyRsr1gz8Q1Q4dYbeDVI0QUMlq5IATlCqD/OxOijaMIS4xQGtj26Lf9ZKqeS81iZwf6t68GeJXNXU0ZZTwD0h0Zmtom4vsQedTXVZS/5WaPdimOSh09AJcftZ+YKX2jlMtCa573espNNrpkn1wTBYMcXK7X4aYnheK7B1bmE6ylaT6Degc+L3e9ltcLp6mxJTHKb3c5GD8ECDWqMyhIs7rDfjKeCprQsIbZ9aSi8ryLeiXEyGsqq25KRzN6+YLpGBic6Oc71y985/ZmTqZHidJXSvdC9MsDPhA9a3uBhHBlQCqei7iwArRAYdDRfgOyg1CcZy+8GmtMC7h+12o1x5ygkFPDGR1yM0q/buvZBJokmaKDL66pFvG4iA31X2ozP07x+fO4U3q4DnXqfQiJP/a0qGCLebmk6vYiUVg7TmYD5n/uaBTQURPDKbNUSg7+I3emHWZqgUwESeotRYbXr5N+Gpnom6gyRMT/VRWcs=
addons:
  code_climate:
    repo_token:
      secure: YIq1sGezTWTNkSgO8XdOxk4d6Q4TUsErCimSUV+ouZ4od5V37ciQBEk8s9Zgp07bDlnu+z4h1q9UBWKq9HXBRyjGPqHjHMuxtH0UWj3/EyCm+BXuHFYHM4b5mImo8yubwFaqgmqAvNbm9/1OOLbe5KhyT1KpEnrQK0qzNCJR7ezIPoymTdgl8/HOsmDbfR/5BoVxiCaDOMdVBYgLQyeuIp8n7mecTqxfZuaY0WQb4uHWViToXLT1MC0Q26Nu4l48tUeFSkgOIAJUq/S4uVDE9FQ7oTvGkCmPm+4csoIRhaZXlwNIEQsfgAM4u4QwF0OY3d2aC0db06cqSHPXsdFzD3N8V8aNjOxllEKn/m9LLmrbRRj+n3n9+bPtVuBcRog4CrZcrBJCT/eY0Qya604gwFNTSBw1r7ybX3WXVNIJv9LMrM0MPFUyZO3Hk4bYxpQ9vLnP7vzC4s4uAb7OIt9R2rhLTjn7zLOi4NIWqfxHxvHoI3idyphM4XB7Wa8EQApFspT0Gom0wNirtp+ViplvQ1kQ0UNqHpp2s3peyntwLvo1tcQRiz8E6dyoMiBHG4geV3s+3ISCyuCColyIbFimqnKz1oShmvSWgnZyY1X7EkHg1quafV0b/LGM1gHTKEsoCXCWMDdNXIrQ+dxxc22rgkWdIOXfEoGXlskLZATWvkI=
