language: node_js
node_js:
- node
services:
- docker
before_script:
- npm install -g @hapi/lab
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < lcov.info
before_install:
- docker build -t iromain/domain-tracker-api .
- echo $DOCKER_PASSWORD | docker login --username="$DOCKER_USERNAME" --password-stdin
- docker push iromain/domain-tracker-api
deploy:
  provider: heroku
  api_key:
    secure: ly1UTWsW6F1eRDLwKUp4YsAGzsgIvxRQB7GRKfZve0tjUCfV3j5EHL8k7yK111qeAVVBmHcWT2bSwYMQUmyyGN4tXoHgn2euHjuT0BDFrS6VXSXQHn9thDYJMZ1kIPb4138RTk2tB+gqtndSDDHeqbI5NVJfTuPeLbBcg3MCZ9ToqRP7LkitUjqYvDUFXYD97pkpARHrmfE7+uHlyAeFi8GfISmoBZRe9R6nJXu5tIbHhCKks8k3q9lMWgPA7MyATQMoQD+qkwj1wnuX8XRa76weM48usLzEhbrP97iFgCqICbPlVksJuxRX/qoNAlb7OmoAIQVaMOXRhjzFl8M4xc0w1Gb9nHRDNm9PuLwkbxJJ1F3C5Dt+hHE9f/hRqgkWrSn5hOz8ME5T9pu+LZ6RXTe8uhWKXp2hoCVhhk9IPECQaGgWF8wrcXSGecMWv62h57S1B7VvSSNzV51aBFuZK0QT+VYvtZCTSDSscZ6af4wAiprgYkBgS/pcMXUy70mxGWxejzVuBYjTBZhjPBAM8hPZS87bMh8cT+kAdo3ORGv9zmYegBcwysPUfnkDEp6cXVsYu1vrvxsSG4iFnXO8dl5edWw/84/qw5TybCTrAx7bnrabJX3QMtnJAj3Y4ZP12gobvropIIyucOzG8/ydVDbTpCeo7iy3UDjOtg5yV40=
  app: domain-tracker-api
  on:
    repo: iRomain/domain-tracker-api
cache:
  directories:
  - node_modules
env:
  global:
  - NODE_ENV=test
  - DOCKER_USERNAME=iromain
  - secure: HQBofMJRIh7rH3H00SGp/pj1tL1Nb6ZtCXWijkNiVIphac0jwilc0gck6F5WPxdnEbfiDKsQ0BKyqJ/3va1nQ05ZGraCUNjQxdlsBtgf62Q9ZcITMris3nNHfgQ+MFqEhX6qei5Wj9TM6C+Jt6V6ovz/+FsfckBBTq5hMQK+gacb7Snc/b++KCtn/YC8C81l77dKDixOTyO112hkYBrIKFhF7v9BFa1yirmy9LOCuo0M6I7znXfJI9v62Y43JyWISacVUaW3DR+sNMs3nAtjftRq3OjiojosL1p3PPKa9zKma7T02D8KlPBvaThwE2xzYtW8mjcSyyqIIUCfiDn8nJZqVd9Hr6+5FFHu2Dw7Un0VOBAwpRHb1CNKJouIFr2v8TOJgMOsl9QoLZtbA85EWARrlzntTMQyA5mcsf/A9il4/wR0pZeU+4Vrr5eUKuec3sFdg5h6Cu5Fdg1o2vxE6cC0YK1zYsO9RNOWfT5BqcLUVkz4554lpZqTZ92OSHf7jMDLmEAmB4ngPf+D/MRiTgDzFpFZoSxnNo7eUN7MvaetVPT7BRmp6zt6VhTnUsyKpMR6sN5XXBYJLnoFIvL36+p7sXe58vNzc+pIIKO/Hf691o+D8HabMADNkln0tlqyzvAJsCECMdA3yZ75rQH3Rtc6JdhwpBbw9jRF/Ll59W0=
addons:
  code_climate:
    repo_token:
      secure: YIq1sGezTWTNkSgO8XdOxk4d6Q4TUsErCimSUV+ouZ4od5V37ciQBEk8s9Zgp07bDlnu+z4h1q9UBWKq9HXBRyjGPqHjHMuxtH0UWj3/EyCm+BXuHFYHM4b5mImo8yubwFaqgmqAvNbm9/1OOLbe5KhyT1KpEnrQK0qzNCJR7ezIPoymTdgl8/HOsmDbfR/5BoVxiCaDOMdVBYgLQyeuIp8n7mecTqxfZuaY0WQb4uHWViToXLT1MC0Q26Nu4l48tUeFSkgOIAJUq/S4uVDE9FQ7oTvGkCmPm+4csoIRhaZXlwNIEQsfgAM4u4QwF0OY3d2aC0db06cqSHPXsdFzD3N8V8aNjOxllEKn/m9LLmrbRRj+n3n9+bPtVuBcRog4CrZcrBJCT/eY0Qya604gwFNTSBw1r7ybX3WXVNIJv9LMrM0MPFUyZO3Hk4bYxpQ9vLnP7vzC4s4uAb7OIt9R2rhLTjn7zLOi4NIWqfxHxvHoI3idyphM4XB7Wa8EQApFspT0Gom0wNirtp+ViplvQ1kQ0UNqHpp2s3peyntwLvo1tcQRiz8E6dyoMiBHG4geV3s+3ISCyuCColyIbFimqnKz1oShmvSWgnZyY1X7EkHg1quafV0b/LGM1gHTKEsoCXCWMDdNXIrQ+dxxc22rgkWdIOXfEoGXlskLZATWvkI=
